global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:90']
  - job_name: 'prom'
    #metrics_path: /metrics/
    static_configs:
    - targets: ['localhost:50']
