FROM arm64v8/debian:stable-slim

ARG GRAAL_VERSION
ARG JDK_VERSION

#RUN set -xeu && \
#    export DEBIAN_FRONTEND=noninteractive && \
#    apt-get update && \
#    apt-get install -y qemu-user-static openjdk-11-jdk

#RUN ["/usr/bin/qemu-aarch64-static", "-version"]

RUN set -xeu && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates `# stays, not having this is just not useful` \
      curl \
      && \
    mkdir /graalvm && \
    curl -fsSL "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java11-linux-aarch64-22.3.0.tar.gz" \
        | tar -zxC /graalvm --strip-components 1 && \
    find /graalvm -name "*src.zip"  -printf "Deleting %p\n" -exec rm {} + && \
    { test ! -d /graalvm/legal || tar czf /graalvm/legal.tgz /graalvm/legal/; } && \
    { test ! -d /graalvm/legal || rm -r /graalvm/legal; } && \
    rm -rf /graalvm/man `# does not exist in java11 package` && \
    echo Cleaning up... && \
    apt-get remove -y \
        curl \
        && \
    apt-get autoremove -y && \
    apt-get clean && rm -r "/var/lib/apt/lists"/* && \
    echo 'PATH="/graalvm/bin:$PATH"' | install --mode 0644 /dev/stdin /etc/profile.d/graal-on-path.sh && \
    echo OK

# This applies to all container processes. However, `bash -l` will source `/etc/profile` and set $PATH on its own. For this reason, we
# *also* set $PATH in /etc/profile.d/*
ENV PATH=/graalvm/bin:$PATH

RUN set -xeu && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
        gcc \
        g++ \
        libz-dev \
        && \
    gu install native-image && \
    # Cleanup
    apt-get clean && rm -rf "/var/lib/apt/lists/*" && \
    echo OK
RUN set -xeu && \
    gu install -c org.graalvm.python && \
    gu install -c org.graalvm.ruby && \
    gu install js && \
    gu list && \
    echo OK
